version: '3.8'

services:
  cassandra:
    image: cassandra:4.1
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=activity_logs_cluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_START_RPC=true
      - CASSANDRA_NUM_TOKENS=32
      - CASSANDRA_ENDPOINT_SNITCH=SimpleSnitch
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=512M
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10

  init-cassandra:
    image: cassandra:4.1
    volumes:
      - ./init-cassandra.cql:/init-cassandra.cql
      - ./scripts/init-cassandra.sh:/init-cassandra.sh
    command: sh /init-cassandra.sh
    depends_on:
      cassandra:
        condition: service_healthy

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - CASSANDRA_HOSTS=cassandra
      - CASSANDRA_PORT=9042
      - CASSANDRA_KEYSPACE=activity_logs
      - ACTIVITY_LOG_TTL=2592000
    depends_on:
      init-cassandra:
        condition: service_completed_successfully
    restart: on-failure
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  cassandra_data: 